### PR TITLE
Adds missing Windows resource classes

### PR DESCRIPTION
**Pull request by alanjclark**
# Description

> Adds machine executor resource classes for Windows resources.

# Implementation details

> Adding `windows.medium` and other sized resource classes to the list of valid `resource_class` enum values.

# How to validate

> Add a Windows resource class to a Machine executor, such as `windows.medium`, and check that it validates as expected.

### CODE REVIEW

**Review by loderunner — CHANGES_REQUESTED** [review]
Thanks for the PR!

The `publicschema.json` is not used for the validation/autocompletion purposes you are trying to address here.

* Validation of machine executor resource classes begins here: https://github.com/CircleCI-Public/circleci-yaml-language-server/blob/8c75190add027ce3b598fbdf1ab6de07382f321e/pkg/parser/validate/executor.go#L72-L73
* Autocompletion of machine executor resource classes begins here: https://github.com/CircleCI-Public/circleci-yaml-language-server/blob/59480ec46254e3d40d6d4f8513fce25b85a96556/pkg/services/complete/executors.go#L131-L132

It seems we do not handle windows machine executors very thoroughly. 😬 
We'd be happy to receive a contribution to improve our support of Windows machine executors!

----

`publicschema.json` refers to [this file](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/circleciconfig.json) SchemaStore, another community repo.

If you could also open a PR for that schema file, that would be great!

**Comment by imlogang** [comment]
Hey @loderunner! 

I'm a little confused here. `publicschema.json` is completely missing the Windows executor, yet the SchemaStore you mentioned, has them available. (I understand this is the schema our UI Config Editor uses as well.)

https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/circleciconfig.json#L551-L559

From my limited understanding, I believe the issue lies in the fact that we aren't validated Windows resource correctly on this line: 
https://github.com/CircleCI-Public/circleci-yaml-language-server/blob/8c75190add027ce3b598fbdf1ab6de07382f321e/pkg/parser/validate/executor.go#L233

It should instead be something like this, no?
```
var ValidWindowsResourceClasses = []string{
	"windows.medium",
	"windows.large",
	"windows.xlarge",
	"windows.2xlarge",
}
```

If my understanding is correct, happy to open a PR!

**Comment by kelvintaywl** [comment]
@loderunner 

I have limited context to this repository but I am thinking @imlogang 's points above are true.

1. We added [a list of valid windows executors here](https://github.com/CircleCI-Public/circleci-yaml-language-server/commit/f3e63029d8faa99455f171e0aaa99ed49a71d9db)
2. This is then [used for validating the windows executors ](https://github.com/CircleCI-Public/circleci-yaml-language-server/blob/5c374dce7b94dffc2eae72950352dad1b3035f76/pkg/parser/validate/executor.go#L232-L235)

If so, re: a PR, would this then mean:

1. Update the list of valid windows executors with the `windows.` prefix as Logan suggested
2. Update our executor tests to include validating the windows executors (perhaps [here?](https://github.com/CircleCI-Public/circleci-yaml-language-server/blob/5c374dce7b94dffc2eae72950352dad1b3035f76/pkg/parser/executors_test.go))

**Comment by loderunner** [comment]
@kelvintaywl Yes, that seems about right. With the new list and the executor test, we should be able to approve and merge the PR.

**Comment by loderunner** [comment]
All executors resource classes and images have been updated with #293. Closing this issue.

**Pull request closed without merging**
